# This file is published as a static asset at:
#   https://machine-memory.jfa.dev/init-mcp.ps1
#
# MCP-only counterpart to `machine-memory init --mcp`.
# Creates or replaces the managed machine-memory block in ./AGENTS.md so agents
# that only have the remote MCP server (no CLI) follow the same workflow.
#
# Usage:
#   irm https://machine-memory.jfa.dev/init-mcp.ps1 | iex
#
# Environment:
#   MACHINE_MEMORY_AGENTS_MD  Path to write (default AGENTS.md).
#                             Absolute or relative to the current directory.

$ErrorActionPreference = "Stop"

$target = if ($env:MACHINE_MEMORY_AGENTS_MD) { $env:MACHINE_MEMORY_AGENTS_MD } else { "AGENTS.md" }
if ([System.IO.Path]::IsPathRooted($target)) {
  $agentsMd = $target
} else {
  $agentsMd = Join-Path (Get-Location) $target
}

# Managed block must stay in sync with agentsMdContent("mcp") in
# cli/src/cli/commands/agents-md-content.ts (base64 payload below).
$memoryBlockB64 = @'
PCEtLSBtYWNoaW5lLW1lbW9yeTpzdGFydCAtLT4KIyMgUHJvamVjdCBtZW1vcnkKClRoaXMgcHJv
amVjdCB1c2VzIGBtYWNoaW5lLW1lbW9yeWAgdGhyb3VnaCB0aGUgcmVtb3RlIE1DUCBzZXJ2ZXIg
KE9BdXRoIHRvIHRoZSBXb3JrZXIgYC9tY3BgIGVuZHBvaW50KS4gTm8gbG9jYWwgQ0xJIG9yIGBt
YWNoaW5lLW1lbW9yeS5kYmAgaXMgcmVxdWlyZWQuCkFsbCBtZW1vcnkgYWNjZXNzIGdvZXMgdGhy
b3VnaCBNQ1AgdG9vbHM6IGBsaXN0X3JlcG9zaXRvcmllc2AsIGBtZW1vcnlfcXVlcnlgLCBgbWVt
b3J5X2dldGAsIGBtZW1vcnlfbGlzdGAsIGBtZW1vcnlfc2l6ZWAsIGBtZW1vcnlfYWRkYCwgYG1l
bW9yeV91cGRhdGVgLCBgbWVtb3J5X2RlbGV0ZWAuClJlcG9zaXRvcnkgc2NvcGU6IGV2ZXJ5IHRv
b2wgdGhhdCByZWFkcyBvciB3cml0ZXMgYSBzcGVjaWZpYyByZXBvIHJlcXVpcmVzIGFuIGV4YWN0
IGBvd25lci9uYW1lYCBzbHVnLiBUaGVyZSBpcyBubyBkZWZhdWx0LiBSZWFkcyBhcmUgbG9vc2Ug
4oCUIGEgd3Jvbmcgc2x1ZyByZXR1cm5zIGVtcHR5L25vdC1mb3VuZCBhbmQgbm90aGluZyBpcyBs
b3N0LiBXcml0ZXMgYXJlIHN0cmljdCBhbmQgcGVybWFuZW50OiBjb25maXJtIHRoZSBzbHVnIHdp
dGggYGxpc3RfcmVwb3NpdG9yaWVzYCBiZWZvcmUgZXZlcnkgd3JpdGU7IGRlcml2ZSBpdCBmcm9t
IGBnaXQgcmVtb3RlIGdldC11cmwgb3JpZ2luYCB3aGVuIGl0IG1hdGNoZXMgYSBrbm93biBlbnRy
eS4KU2VhcmNoIHBvbGljeTogdXNlIGBtZW1vcnlfcXVlcnlgIHdpdGggYG1vZGU6ICJrZXl3b3Jk
ImAgZm9yIGV4YWN0IG5hbWVzLCBwYXRocywgY29tbWFuZHMsIGFuZCBpZGVudGlmaWVyczsgYG1v
ZGU6ICJzZW1hbnRpYyJgIHdoZW4gdGhlIHNhbWUgY29uY2VwdCBtYXkgdXNlIGRpZmZlcmVudCB3
b3JkaW5nOyBgbW9kZTogImh5YnJpZCJgIChkZWZhdWx0KSBmb3IgYnJvYWQgaW52ZXN0aWdhdGlv
bi4gRmlsdGVyIHdpdGggYHN0YXR1c2AgLyBgbWVtb3J5X3R5cGVgIC8gYGNlcnRhaW50eWAgYW5k
IGNhcCB3aXRoIGBsaW1pdGAgKGRlZmF1bHQgOCwgbWF4IDUwKS4gRDEgcmVjb3JkcyBhcmUgY2Fu
b25pY2FsIGFuZCBWZWN0b3JpemUgaXMgb25seSBhIHJldHJpZXZhbCBpbmRleC4KV3JpdGVzIChg
bWVtb3J5X2FkZGAsIGBtZW1vcnlfdXBkYXRlYCwgYG1lbW9yeV9kZWxldGVgKSBhcmUgcGVybWFu
ZW50LiBgbWVtb3J5X2FkZGAgZWNob2VzIGB3cml0dGVuX3RvYCBwbHVzIHRoZSBuZXcgYGlkYDsg
YG1lbW9yeV9kZWxldGVgIGVjaG9lcyBgZGVsZXRlZF9mcm9tYCB3aXRoIGBkZWxldGVkYCAvIGBl
eGlzdGVkYC4gRW1iZWRkaW5ncyByZS1zeW5jIHRvIFZlY3Rvcml6ZSBhdXRvbWF0aWNhbGx5IG9u
IGFkZC91cGRhdGUuCmBtZW1vcnlfYWRkYCBkZWZhdWx0cyB0byBgbWVtb3J5X3R5cGU6IGNvbnZl
bnRpb25gLCBgY2VydGFpbnR5OiBpbmZlcnJlZGAsIGBzdGF0dXM6IGFjdGl2ZWAg4oCUIHNldCB0
aGVtIGV4cGxpY2l0bHkgKGBkZWNpc2lvbmAgLyBgcmVmZXJlbmNlYCAvIGBnb3RjaGFgOyBgdmVy
aWZpZWRgIC8gYGluZmVycmVkYCkuIGBleHBpcmVzX2FmdGVyX2RheXNgIGlzIG9ubHkgdmFsaWQg
Zm9yIGBzdGF0dXNgIG1lbW9yaWVzIGFuZCBjYW4gb25seSBiZSBzZXQgYXQgY3JlYXRpb24uCk1l
bW9yeSBzaXplOiB0aGUgY29tcG9zZWQgZW1iZWRkaW5nIHRleHQgbXVzdCBzdGF5IHdpdGhpbiB0
aGUgV29ya2VyJ3MgY29uc2VydmF0aXZlIGJ5dGUrMiBidWRnZXQgKFVURi04IGJ5dGVzICsgMiDi
iaQgNTEyKS4gUHJlZmxpZ2h0IHdpdGhvdXQgd3JpdGluZzogY2FsbCBgbWVtb3J5X3NpemVgIHdp
dGggdGhlIHByb3NwZWN0aXZlIGNvbnRlbnQvdGFncy9jb250ZXh0L3R5cGUuIEl0IHRha2VzIG5v
IHJlcG9zaXRvcnkgYW5kIHVzZXMgdGhlIHNhbWUgZGVmYXVsdHMgYXMgYG1lbW9yeV9hZGRgLCBz
byBwYXNzIHRoZSB0eXBlL2NlcnRhaW50eS9zdGF0dXMgeW91IGludGVuZCB0byB3cml0ZS4gYG1l
bW9yeV9hZGRgIGFuZCBgbWVtb3J5X3VwZGF0ZWAgcmVqZWN0IG9uIGZsaWdodCB3aGVuIG92ZXIg
YnVkZ2V0OyBvdmVyc2l6ZSBgbWVtb3J5X3NpemVgIHJlc3VsdHMgc2V0IGBpc0Vycm9yYCBhbmQg
aW5jbHVkZSBgb3Zlcl9ieV9ieXRlc2AuCgrimqDvuI8gTUFOREFUT1JZOiBDb21wbGV0ZSB0aGUg
bWVtb3J5IHNjYW4gQkVGT1JFIGFueSBjb2RlIGNoYW5nZXMuIFNraXBwaW5nIGl0IGNhdXNlcyBy
ZXdvcmssIHJlZ3Jlc3Npb25zLCBhbmQgZHVwbGljYXRlZCBkZWNpc2lvbnMuCgojIyMgUmVxdWly
ZWQgcHJlLXdvcmtmbG93IChETyBOT1QgU0tJUCkKCkJlZm9yZSB0b3VjaGluZyBjb2RlLCBjb21w
bGV0ZSB0aGlzIHNjYW4gdmlhIE1DUCB0b29scy4gVGhlcmUgaXMgbm8gYHN1Z2dlc3RgIHRvb2wg
4oCUIGVtdWxhdGUgZmlsZS1zY29wZWQgbG9va3VwIHdpdGggYG1lbW9yeV9xdWVyeWAgaW4gYGtl
eXdvcmRgIG1vZGUgdXNpbmcgcGF0aHMgYW5kIGlkZW50aWZpZXJzIGFzIGtleXdvcmRzOgoKLSBL
bm93biBmaWxlczogYG1lbW9yeV9xdWVyeWAgd2l0aCBgeyByZXBvc2l0b3J5LCBxdWVyeTogInBh
dGgvYS50cyBpZGVudGlmaWVyIiwgbW9kZTogImtleXdvcmQiIH1gCi0gS25vd24gdG9waWM6IGBt
ZW1vcnlfcXVlcnlgIHdpdGggYHsgcmVwb3NpdG9yeSwgcXVlcnk6ICJ0b3BpYyIsIG1vZGU6ICJo
eWJyaWQiIH1gCi0gQnJvYWQgYXVkaXQ6IGBtZW1vcnlfbGlzdGAgd2l0aCBgeyByZXBvc2l0b3J5
IH1gIChmaWx0ZXIgYnkgYG1lbW9yeV90eXBlYCAvIGBzdGF0dXNgIC8gYGNlcnRhaW50eWA7IGl0
IGhhcyBubyB0YWdzIGZpbHRlcikgb3IgYG1lbW9yeV9xdWVyeWAgd2l0aCB0YWctb3JpZW50ZWQg
a2V5d29yZHMKLSBEaXNjb3ZlciBzbHVnOiBgbGlzdF9yZXBvc2l0b3JpZXNgIHdoZW4gdGhlIGBv
d25lci9uYW1lYCBpcyBub3QgY2VydGFpbgoKSWYgcmVzdWx0cyBsb29rIHJlbGV2YW50LCBmZXRj
aCBmdWxsIHJlY29yZHMgYmVmb3JlIGVkaXRpbmc6IGBtZW1vcnlfZ2V0YCB3aXRoIGB7IHJlcG9z
aXRvcnksIGlkIH1gIChvbmUgaWQgcGVyIGNhbGwpLgoKIyMjIE9uZS1zd2VlcCB3b3JrZmxvdyAo
dXNlIHRoaXMgZXZlcnkgdGFzaykKCjEuIFNjYW4gcmVsZXZhbnQgY29udGV4dCBmYXN0LiBSdW4g
ZXhhY3RseSBvbmUgZm9jdXNlZCBgbWVtb3J5X3F1ZXJ5YCBvciBgbWVtb3J5X2xpc3RgIGJlZm9y
ZSBjb2RlIGNoYW5nZXM7IHJlcGVhdCBvbmx5IGlmIHRoZSB0b3VjaGVkIHBhdGhzIG9yIHNjb3Bl
IG1hdGVyaWFsbHkgY2hhbmdlcy4KMi4gVmVyaWZ5IHVuY2VydGFpbiBjb250ZXh0IGJlZm9yZSBh
Y3RpbmcuIFRoZXJlIGFyZSBubyBgdmVyaWZ5YCAvIGBkaWZmYCB0b29scyDigJQgcmUtcmVhZCBj
YW5kaWRhdGVzIHdpdGggYG1lbW9yeV9nZXRgIGFuZCBjb21wYXJlIGFnYWluc3QgdGhlIGNvZGUs
IHRoZW4gcHJlZmVyIGBtZW1vcnlfdXBkYXRlYCBvbiB0aGUgY2Fub25pY2FsIGlkIHdoZW4gd29y
ZGluZyBtdXN0IGNoYW5nZTsgZG8gbm90IGNyZWF0ZSBkdXBsaWNhdGVzLgozLiBNYWludGFpbiBt
ZW1vcnkgd2hpbGUgaW1wbGVtZW50aW5nLiBQcmVmZXIgYG1lbW9yeV91cGRhdGVgIHdpdGggdGhl
IGV4YWN0IGBpZGAgKHRoZXJlIGlzIG5vIG1hdGNoL3Vwc2VydCDigJQgcmVzb2x2ZSB0aGUgaWQg
dmlhIHF1ZXJ5IGZpcnN0OyBvbmx5IGNoYW5nZWQgZmllbGRzIGFyZSBuZWVkZWQpLiBJZiBubyBy
ZWxpYWJsZSBtYXRjaCBleGlzdHMsIGBtZW1vcnlfYWRkYCB3aXRoIGNsZWFyIHRhZ3MgKGBhcmVh
OuKApix0b3BpYzrigKYsa2luZDrigKZgKS4gQ2FsbCBgbWVtb3J5X3NpemVgIGZpcnN0IHdoZW4g
Y29udGVudCBtYXkgYmUgbG9uZy4KNC4gV3JpdGUgZm9yIHJldHJpZXZhbC4gUHV0IGNvbW1hbmRz
LCBBUEkgcGF0aHMsIGZpbGUgcGF0aHMsIGtleXMsIHJvdXRlcywgdGhyZXNob2xkcywgYW5kIGV4
YWN0IGZlYXR1cmUga2V5d29yZHMgaW4gdGhlIGZpcnN0IHNlbnRlbmNlIG9mIGBjb250ZW50YC4K
NS4gVXNlIHBhdGgtZHJpdmVuIHRhZ3MuIFRoZXJlIGlzIG5vIHRhZy1tYXAgdG9vbCDigJQgdGFn
cyBhcmUgZnJlZS1mb3JtIGNvbW1hLXNlcGFyYXRlZCB0ZXh0LCBzbyB1c2Ugc2NvcGVkIHRhZ3Mg
c3VjaCBhcyBgYXJlYTpjbGksdG9waWM6YmFja2VuZCxraW5kOmRlY2lzaW9uYC4gYG1lbW9yeV9s
aXN0YCBjYW5ub3QgZmlsdGVyIGJ5IHRhZ3M7IGF1ZGl0IHRhZyB1c2FnZSB2aWEgYG1lbW9yeV9x
dWVyeWAuCjYuIENhcHR1cmUgdGhpcmQtcGFydHkgcXVpcmtzLiBBbHdheXMgYWRkIGEgYG1lbW9y
eV90eXBlOiAiZ290Y2hhImAgbWVtb3J5IGZvciBzdXJwcmlzaW5nIGxpYnJhcnkgb3IgdG9vbCBi
ZWhhdmlvciwgbGVhZGluZyB3aXRoIHRoZSBsaWJyYXJ5IG5hbWUsIGJlaGF2aW9yLCBhbmQgZml4
Lgo3LiBLZWVwIHN0YXR1cyBoeWdpZW5lLiBTdGF0dXMgbWVtb3JpZXMgYXJlIGZvciB0cmFuc2ll
bnQgcHJvZ3Jlc3MsIHNob3VsZCBzZXQgYGV4cGlyZXNfYWZ0ZXJfZGF5c2AgYXQgY3JlYXRpb24s
IGFuZCBzaG91bGQgYmUgdXBkYXRlZCByYXRoZXIgdGhhbiBkdXBsaWNhdGVkLiAoYG1lbW9yeV91
cGRhdGVgIGNhbm5vdCBzZXQgZXhwaXJ5LikKOC4gU2VwYXJhdGUgZHVyYWJsZSBhbmQgdHJhbnNp
ZW50IGZhY3RzLiBVc2UgYGRlY2lzaW9uYCwgYHJlZmVyZW5jZWAsIG9yIGBnb3RjaGFgIGZvciBy
ZXVzYWJsZSBrbm93bGVkZ2U7IHVzZSBgc3RhdHVzYCBvbmx5IGZvciBzaG9ydC1saXZlZCBzbmFw
c2hvdHMuCjkuIEF0IHRhc2sgZW5kLCBwZXJzaXN0IGV2ZXJ5IGR1cmFibGUgZGVjaXNpb24sIGNv
bnN0cmFpbnQsIHByZWZlcmVuY2UsIG5vbi1vYnZpb3VzIGdvdGNoYSwgYW5kIHZlcmlmaWVkIHN0
YXR1cyBmdXR1cmUgc2Vzc2lvbnMgbmVlZCB2aWEgYG1lbW9yeV9hZGRgIC8gYG1lbW9yeV91cGRh
dGVgLiBEbyBub3Qgc3RvcmUgb2J2aW91cyBjb2RlIGZhY3RzLCByb3V0aW5lIHRlc3QgcmVzdWx0
cywgdGVtcG9yYXJ5IHByb2dyZXNzLCBvciBkdXBsaWNhdGVzLgoKIyMjIENoZWNrbGlzdCAodmVy
aWZ5IGJlZm9yZSBwcm9jZWVkaW5nKQoKLSBbIF0gSSByYW4gYG1lbW9yeV9xdWVyeWAgb3IgYG1l
bW9yeV9saXN0YCAoYW5kIGBsaXN0X3JlcG9zaXRvcmllc2AgaWYgdGhlIHNsdWcgd2FzIHVuY2Vy
dGFpbikgZm9yIHRoZSBmaWxlcyBvciBmZWF0dXJlIEkgd2lsbCB0b3VjaAotIFsgXSBJIHJldmll
d2VkIHRoZSByZXR1cm5lZCBtZW1vcnkgSURzIGFuZCBmZXRjaGVkIGZ1bGwgcmVjb3JkcyB3aXRo
IGBtZW1vcnlfZ2V0YCB3aGVuIHJlbGV2YW50Ci0gWyBdIEkgY29uc2lkZXJlZCB3aGV0aGVyIGV4
aXN0aW5nIG1lbW9yaWVzIGNvbnN0cmFpbiB0aGUgcGxhbm5lZCBhcHByb2FjaAotIFsgXSBJIHdp
bGwgZG9jdW1lbnQgc2lnbmlmaWNhbnQgZmluZGluZ3MgYW5kIGRlY2lzaW9ucyBhZnRlciBjb21w
bGV0aW5nIHRoZSB0YXNrCgpQcm9qZWN0IHByZWZlcmVuY2U6IHJlcGxhY2Ugb2Jzb2xldGUgc3lz
dGVtcyB3aGVuIHByYWN0aWNhbDsgcHJlc2VydmUgYmFja3dhcmRzIGNvbXBhdGliaWxpdHkgb25s
eSB3aGVuIGl0IGlzIGV4cGxpY2l0bHkgcmVxdWlyZWQuCjwhLS0gbWFjaGluZS1tZW1vcnk6ZW5k
IC0tPg==
'@

$cleanB64 = $memoryBlockB64 -replace '\s', ''
try {
  $managedBlock = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($cleanB64))
} catch {
  throw "machine-memory init-mcp: could not decode managed AGENTS.md block. $_"
}
if (-not $managedBlock.EndsWith("`n")) {
  $managedBlock += "`n"
}

$startMarker = '<!-- machine-memory:start -->'
$endMarker = '<!-- machine-memory:end -->'

if (Test-Path -LiteralPath $agentsMd -PathType Leaf) {
  $existing = [System.IO.File]::ReadAllText($agentsMd)
  $action = 'Updated'
} else {
  $existing = ''
  $action = 'Created'
  $parentDir = Split-Path -Parent $agentsMd
  if ($parentDir -and -not (Test-Path -LiteralPath $parentDir)) {
    New-Item -ItemType Directory -Force -Path $parentDir | Out-Null
  }
}

$s = $existing.IndexOf($startMarker)
$e = if ($s -ge 0) { $existing.IndexOf($endMarker, $s) } else { -1 }
if ($s -ge 0 -and $e -ge 0) {
  $after = $existing.Substring($e + $endMarker.Length)
  $out = $existing.Substring(0, $s) + $managedBlock.TrimEnd("`r", "`n") + "`n"
  if ($after) {
    $out += $after.TrimStart("`r", "`n")
    if (-not $out.EndsWith("`n")) {
      $out += "`n"
    }
  }
} else {
  $body = $existing.TrimEnd()
  $managedTrimmed = $managedBlock.TrimEnd("`r", "`n")
  if ($body) {
    $out = "$body`n`n$managedTrimmed`n"
  } else {
    $out = "$managedTrimmed`n"
  }
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($agentsMd, $out, $utf8NoBom)

Write-Host "$action $agentsMd"
Write-Host "Backend  mcp (MCP tools; no CLI)"
Write-Host "Next     connect an OAuth MCP client to https://<worker-url>/mcp"
Write-Host "Docs     https://machine-memory.jfa.dev/mcp/init"
