# This file is published as a static asset at:
#   https://machine-memory.jfa.dev/init-mcp.ps1
#
# MCP-only counterpart to `machine-memory init --mcp`.
# Creates or replaces the managed machine-memory block in ./AGENTS.md so agents
# that only have the remote MCP server (no CLI) follow the same workflow.
#
# Usage:
#   irm https://machine-memory.jfa.dev/init-mcp.ps1 | iex
#
# Environment:
#   MACHINE_MEMORY_AGENTS_MD  Path to write (default AGENTS.md).
#                             Absolute or relative to the current directory.

$ErrorActionPreference = "Stop"

$target = if ($env:MACHINE_MEMORY_AGENTS_MD) { $env:MACHINE_MEMORY_AGENTS_MD } else { "AGENTS.md" }
if ([System.IO.Path]::IsPathRooted($target)) {
  $agentsMd = $target
} else {
  $agentsMd = Join-Path (Get-Location) $target
}

# Managed block must stay in sync with agentsMdContent("mcp") in
# cli/src/cli/commands/agents-md-content.ts (base64 payload below).
$memoryBlockB64 = @'
PCEtLSBtYWNoaW5lLW1lbW9yeTpzdGFydCAtLT4KIyMgUHJvamVjdCBtZW1vcnkKClRoaXMgcHJv
amVjdCB1c2VzIGBtYWNoaW5lLW1lbW9yeWAgdGhyb3VnaCB0aGUgcmVtb3RlIE1DUCBzZXJ2ZXIg
KE9BdXRoIHRvIHRoZSBXb3JrZXIgYC9tY3BgIGVuZHBvaW50KS4gTm8gbG9jYWwgQ0xJIG9yIGBt
YWNoaW5lLW1lbW9yeS5kYmAgaXMgcmVxdWlyZWQuCkFsbCBtZW1vcnkgYWNjZXNzIGdvZXMgdGhy
b3VnaCBNQ1AgdG9vbHM6IGBsaXN0X3JlcG9zaXRvcmllc2AsIGBtZW1vcnlfc3VnZ2VzdGAsIGBt
ZW1vcnlfcXVlcnlgLCBgbWVtb3J5X2dldGAsIGBtZW1vcnlfbGlzdGAsIGBtZW1vcnlfdmVyaWZ5
YCwgYG1lbW9yeV9kaWZmYCwgYG1lbW9yeV9zaXplYCwgYG1lbW9yeV9hZGRgLCBgbWVtb3J5X3Vw
ZGF0ZWAsIGBtZW1vcnlfZGVsZXRlYC4KUmVwb3NpdG9yeSBzY29wZTogZXZlcnkgdG9vbCB0aGF0
IHJlYWRzIG9yIHdyaXRlcyBhIHNwZWNpZmljIHJlcG8gcmVxdWlyZXMgYW4gZXhhY3QgYG93bmVy
L25hbWVgIHNsdWcuIFRoZXJlIGlzIG5vIGRlZmF1bHQuIFJlYWRzIGFyZSBsb29zZSDigJQgYSB3
cm9uZyBzbHVnIHJldHVybnMgZW1wdHkvbm90LWZvdW5kIGFuZCBub3RoaW5nIGlzIGxvc3QuIFdy
aXRlcyBhcmUgc3RyaWN0IGFuZCBwZXJtYW5lbnQ6IGNvbmZpcm0gdGhlIHNsdWcgd2l0aCBgbGlz
dF9yZXBvc2l0b3JpZXNgIGJlZm9yZSBldmVyeSB3cml0ZTsgZGVyaXZlIGl0IGZyb20gYGdpdCBy
ZW1vdGUgZ2V0LXVybCBvcmlnaW5gIHdoZW4gaXQgbWF0Y2hlcyBhIGtub3duIGVudHJ5LgpTZWFy
Y2ggcG9saWN5OiBgbWVtb3J5X3N1Z2dlc3RgIHdpdGggYHsgcmVwb3NpdG9yeSwgZmlsZXMgfWAg
Zm9yIGZpbGUtc2NvcGVkIGxvb2t1cDsgYG1lbW9yeV9xdWVyeWAgd2l0aCBgbW9kZTogImtleXdv
cmQiYCBmb3IgZXhhY3QgbmFtZXMsIHBhdGhzLCBjb21tYW5kcywgYW5kIGlkZW50aWZpZXJzLCBg
bW9kZTogInNlbWFudGljImAgd2hlbiB0aGUgc2FtZSBjb25jZXB0IG1heSB1c2UgZGlmZmVyZW50
IHdvcmRpbmcsIGBtb2RlOiAiaHlicmlkImAgKGRlZmF1bHQpIGZvciBicm9hZCBpbnZlc3RpZ2F0
aW9uLiBGaWx0ZXIgd2l0aCBgdGFnc2AgKHN1YnN0cmluZykgLyBgc3RhdHVzYCAvIGBtZW1vcnlf
dHlwZWAgLyBgY2VydGFpbnR5YCBhbmQgY2FwIHdpdGggYGxpbWl0YCAoZGVmYXVsdCA4LCBtYXgg
NTApLiBEMSByZWNvcmRzIGFyZSBjYW5vbmljYWwgYW5kIFZlY3Rvcml6ZSBpcyBvbmx5IGEgcmV0
cmlldmFsIGluZGV4LgpXcml0ZXMgKGBtZW1vcnlfYWRkYCwgYG1lbW9yeV91cGRhdGVgLCBgbWVt
b3J5X2RlbGV0ZWApIGFyZSBwZXJtYW5lbnQuIGBtZW1vcnlfYWRkYCBlY2hvZXMgYHdyaXR0ZW5f
dG9gIHBsdXMgdGhlIG5ldyBgaWRgIGFuZCBgcG90ZW50aWFsX2NvbmZsaWN0c2A7IGBtZW1vcnlf
ZGVsZXRlYCBlY2hvZXMgYGRlbGV0ZWRfZnJvbWAgd2l0aCBgZGVsZXRlZGAgLyBgZXhpc3RlZGAu
IEVtYmVkZGluZ3MgcmUtc3luYyB0byBWZWN0b3JpemUgYXV0b21hdGljYWxseSBvbiBhZGQvdXBk
YXRlLgpgbWVtb3J5X2FkZGAgZGVmYXVsdHMgdG8gYG1lbW9yeV90eXBlOiBjb252ZW50aW9uYCwg
YGNlcnRhaW50eTogaW5mZXJyZWRgLCBgc3RhdHVzOiBhY3RpdmVgIOKAlCBzZXQgdGhlbSBleHBs
aWNpdGx5IChgZGVjaXNpb25gIC8gYHJlZmVyZW5jZWAgLyBgZ290Y2hhYDsgYHZlcmlmaWVkYCAv
IGBpbmZlcnJlZGApLiBgZXhwaXJlc19hZnRlcl9kYXlzYCBpcyBvbmx5IHZhbGlkIGZvciBgc3Rh
dHVzYCBtZW1vcmllcy4gUHJlZmVyIGBtZW1vcnlfYWRkYCB3aXRoIGB1cHNlcnRfbWF0Y2hgIChz
dHJvbmcgbWF0Y2hlcyB1cGRhdGUgaW4gcGxhY2U7IHdlYWsgbWF0Y2hlcyByZWZ1c2UgdW5sZXNz
IGBmb3JjZTogdHJ1ZWApIGFuZCBgbWVtb3J5X3VwZGF0ZWAgd2l0aCBgbWF0Y2hgIG92ZXIgcmF3
IGNyZWF0ZXMuCk1lbW9yeSBzaXplOiB0aGUgY29tcG9zZWQgZW1iZWRkaW5nIHRleHQgbXVzdCBz
dGF5IHdpdGhpbiB0aGUgV29ya2VyJ3MgY29uc2VydmF0aXZlIGJ5dGUrMiBidWRnZXQgKFVURi04
IGJ5dGVzICsgMiDiiaQgNTEyKS4gUHJlZmxpZ2h0IHdpdGhvdXQgd3JpdGluZzogY2FsbCBgbWVt
b3J5X3NpemVgIHdpdGggdGhlIHByb3NwZWN0aXZlIGNvbnRlbnQvdGFncy9jb250ZXh0L3R5cGUu
IEl0IHRha2VzIG5vIHJlcG9zaXRvcnkgYW5kIHVzZXMgdGhlIHNhbWUgZGVmYXVsdHMgYXMgYG1l
bW9yeV9hZGRgLCBzbyBwYXNzIHRoZSB0eXBlL2NlcnRhaW50eS9zdGF0dXMgeW91IGludGVuZCB0
byB3cml0ZS4gYG1lbW9yeV9hZGRgIGFuZCBgbWVtb3J5X3VwZGF0ZWAgcmVqZWN0IG9uIGZsaWdo
dCB3aGVuIG92ZXIgYnVkZ2V0OyBvdmVyc2l6ZSBgbWVtb3J5X3NpemVgIHJlc3VsdHMgc2V0IGBp
c0Vycm9yYCBhbmQgaW5jbHVkZSBgb3Zlcl9ieV9ieXRlc2AuCgrimqDvuI8gTUFOREFUT1JZOiBD
b21wbGV0ZSB0aGUgbWVtb3J5IHNjYW4gQkVGT1JFIGFueSBjb2RlIGNoYW5nZXMuIFNraXBwaW5n
IGl0IGNhdXNlcyByZXdvcmssIHJlZ3Jlc3Npb25zLCBhbmQgZHVwbGljYXRlZCBkZWNpc2lvbnMu
CgojIyMgUmVxdWlyZWQgcHJlLXdvcmtmbG93IChETyBOT1QgU0tJUCkKCkJlZm9yZSB0b3VjaGlu
ZyBjb2RlLCBjb21wbGV0ZSB0aGlzIHNjYW4gdmlhIE1DUCB0b29sczoKCi0gS25vd24gZmlsZXM6
IGBtZW1vcnlfc3VnZ2VzdGAgd2l0aCBgeyByZXBvc2l0b3J5LCBmaWxlczogInBhdGgvYS50cyxw
YXRoL2IudHMiIH1gCi0gS25vd24gdG9waWM6IGBtZW1vcnlfcXVlcnlgIHdpdGggYHsgcmVwb3Np
dG9yeSwgcXVlcnk6ICJ0b3BpYyIsIG1vZGU6ICJoeWJyaWQiIH1gCi0gQnJvYWQgYXVkaXQ6IGBt
ZW1vcnlfbGlzdGAgd2l0aCBgeyByZXBvc2l0b3J5IH1gIChmaWx0ZXIgYnkgYHRhZ3NgIC8gYG1l
bW9yeV90eXBlYCAvIGBzdGF0dXNgIC8gYGNlcnRhaW50eWApIG9yIGBtZW1vcnlfcXVlcnlgIHdp
dGggdGFnLW9yaWVudGVkIGtleXdvcmRzCi0gRGlzY292ZXIgc2x1ZzogYGxpc3RfcmVwb3NpdG9y
aWVzYCB3aGVuIHRoZSBgb3duZXIvbmFtZWAgaXMgbm90IGNlcnRhaW4KCklmIHJlc3VsdHMgbG9v
ayByZWxldmFudCwgZmV0Y2ggZnVsbCByZWNvcmRzIGJlZm9yZSBlZGl0aW5nOiBgbWVtb3J5X2dl
dGAgd2l0aCBgeyByZXBvc2l0b3J5LCBpZCB9YCAob25lIGlkIHBlciBjYWxsKS4KCiMjIyBPbmUt
c3dlZXAgd29ya2Zsb3cgKHVzZSB0aGlzIGV2ZXJ5IHRhc2spCgoxLiBTY2FuIHJlbGV2YW50IGNv
bnRleHQgZmFzdC4gUnVuIGV4YWN0bHkgb25lIGZvY3VzZWQgYG1lbW9yeV9zdWdnZXN0YCwgYG1l
bW9yeV9xdWVyeWAsIG9yIGBtZW1vcnlfbGlzdGAgYmVmb3JlIGNvZGUgY2hhbmdlczsgcmVwZWF0
IG9ubHkgaWYgdGhlIHRvdWNoZWQgcGF0aHMgb3Igc2NvcGUgbWF0ZXJpYWxseSBjaGFuZ2VzLgoy
LiBWZXJpZnkgdW5jZXJ0YWluIGNvbnRleHQgYmVmb3JlIGFjdGluZy4gVXNlIGBtZW1vcnlfdmVy
aWZ5YCB3aXRoIGB7IHJlcG9zaXRvcnksIGlkLCBmYWN0IH1gIG9yIGBtZW1vcnlfZGlmZmAgd2l0
aCBgeyByZXBvc2l0b3J5LCBpZCwgY29udGVudCB9YCB3aGVuIGFuIGluZmVyZW5jZSBtYXkgY29u
ZmxpY3Qgd2l0aCBleGlzdGluZyBtZW1vcnkuCjMuIE1haW50YWluIG1lbW9yeSB3aGlsZSBpbXBs
ZW1lbnRpbmcuIFByZWZlciBgbWVtb3J5X3VwZGF0ZWAgd2l0aCBgbWF0Y2hgIChvciB0aGUgZXhh
Y3QgYGlkYDsgb25seSBjaGFuZ2VkIGZpZWxkcyBhcmUgbmVlZGVkKTsgaWYgbm8gcmVsaWFibGUg
bWF0Y2ggZXhpc3RzLCB1c2UgYG1lbW9yeV9hZGRgIHdpdGggYHVwc2VydF9tYXRjaGAuIFdlYWsg
dXBzZXJ0IG1hdGNoZXMgcmVmdXNlIHRvIHNpbGVudGx5IGNyZWF0ZTogaW5zcGVjdCB3aXRoIGBt
ZW1vcnlfZ2V0YCwgdGhlbiBwYXNzIGBmb3JjZTogdHJ1ZWAgaWYgYSBuZXcgcmVjb3JkIGlzIGlu
dGVuZGVkLiBDYWxsIGBtZW1vcnlfc2l6ZWAgZmlyc3Qgd2hlbiBjb250ZW50IG1heSBiZSBsb25n
Lgo0LiBXcml0ZSBmb3IgcmV0cmlldmFsLiBQdXQgY29tbWFuZHMsIEFQSSBwYXRocywgZmlsZSBw
YXRocywga2V5cywgcm91dGVzLCB0aHJlc2hvbGRzLCBhbmQgZXhhY3QgZmVhdHVyZSBrZXl3b3Jk
cyBpbiB0aGUgZmlyc3Qgc2VudGVuY2Ugb2YgYGNvbnRlbnRgLgo1LiBVc2UgcGF0aC1kcml2ZW4g
dGFncy4gVGhlcmUgaXMgbm8gdGFnLW1hcCB0b29sIOKAlCB0YWdzIGFyZSBmcmVlLWZvcm0gY29t
bWEtc2VwYXJhdGVkIHRleHQsIHNvIHVzZSBzY29wZWQgdGFncyBzdWNoIGFzIGBhcmVhOmNsaSx0
b3BpYzpiYWNrZW5kLGtpbmQ6ZGVjaXNpb25gLiBGaWx0ZXIgdGhlbSB3aXRoIHRoZSBgdGFnc2Ag
cGFyYW1ldGVyIG9uIHF1ZXJ5L2xpc3Qvc3VnZ2VzdC4KNi4gQ2FwdHVyZSB0aGlyZC1wYXJ0eSBx
dWlya3MuIEFsd2F5cyBhZGQgYSBgbWVtb3J5X3R5cGU6ICJnb3RjaGEiYCBtZW1vcnkgZm9yIHN1
cnByaXNpbmcgbGlicmFyeSBvciB0b29sIGJlaGF2aW9yLCBsZWFkaW5nIHdpdGggdGhlIGxpYnJh
cnkgbmFtZSwgYmVoYXZpb3IsIGFuZCBmaXguCjcuIEtlZXAgc3RhdHVzIGh5Z2llbmUuIFN0YXR1
cyBtZW1vcmllcyBhcmUgZm9yIHRyYW5zaWVudCBwcm9ncmVzcywgc2hvdWxkIHNldCBgZXhwaXJl
c19hZnRlcl9kYXlzYCAoYXQgY3JlYXRpb24gb3IgdmlhIGBtZW1vcnlfdXBkYXRlYCksIGFuZCBz
aG91bGQgYmUgdXBkYXRlZCByYXRoZXIgdGhhbiBkdXBsaWNhdGVkLiBEZXByZWNhdGUgdmlhIGBt
ZW1vcnlfdXBkYXRlYCB3aXRoIGBzdGF0dXNgIChhbmQgYHN1cGVyc2VkZWRfYnlgIHdoZW4gcmVw
bGFjZWQpLgo4LiBTZXBhcmF0ZSBkdXJhYmxlIGFuZCB0cmFuc2llbnQgZmFjdHMuIFVzZSBgZGVj
aXNpb25gLCBgcmVmZXJlbmNlYCwgb3IgYGdvdGNoYWAgZm9yIHJldXNhYmxlIGtub3dsZWRnZTsg
dXNlIGBzdGF0dXNgIG9ubHkgZm9yIHNob3J0LWxpdmVkIHNuYXBzaG90cy4KOS4gQXQgdGFzayBl
bmQsIHBlcnNpc3QgZXZlcnkgZHVyYWJsZSBkZWNpc2lvbiwgY29uc3RyYWludCwgcHJlZmVyZW5j
ZSwgbm9uLW9idmlvdXMgZ290Y2hhLCBhbmQgdmVyaWZpZWQgc3RhdHVzIGZ1dHVyZSBzZXNzaW9u
cyBuZWVkIHZpYSBgbWVtb3J5X2FkZGAgLyBgbWVtb3J5X3VwZGF0ZWAuIERvIG5vdCBzdG9yZSBv
YnZpb3VzIGNvZGUgZmFjdHMsIHJvdXRpbmUgdGVzdCByZXN1bHRzLCB0ZW1wb3JhcnkgcHJvZ3Jl
c3MsIG9yIGR1cGxpY2F0ZXMuCgojIyMgQ2hlY2tsaXN0ICh2ZXJpZnkgYmVmb3JlIHByb2NlZWRp
bmcpCgotIFsgXSBJIHJhbiBgbWVtb3J5X3N1Z2dlc3RgLCBgbWVtb3J5X3F1ZXJ5YCwgb3IgYG1l
bW9yeV9saXN0YCAoYW5kIGBsaXN0X3JlcG9zaXRvcmllc2AgaWYgdGhlIHNsdWcgd2FzIHVuY2Vy
dGFpbikgZm9yIHRoZSBmaWxlcyBvciBmZWF0dXJlIEkgd2lsbCB0b3VjaAotIFsgXSBJIHJldmll
d2VkIHRoZSByZXR1cm5lZCBtZW1vcnkgSURzIGFuZCBmZXRjaGVkIGZ1bGwgcmVjb3JkcyB3aXRo
IGBtZW1vcnlfZ2V0YCB3aGVuIHJlbGV2YW50Ci0gWyBdIEkgY29uc2lkZXJlZCB3aGV0aGVyIGV4
aXN0aW5nIG1lbW9yaWVzIGNvbnN0cmFpbiB0aGUgcGxhbm5lZCBhcHByb2FjaAotIFsgXSBJIHdp
bGwgZG9jdW1lbnQgc2lnbmlmaWNhbnQgZmluZGluZ3MgYW5kIGRlY2lzaW9ucyBhZnRlciBjb21w
bGV0aW5nIHRoZSB0YXNrCgpQcm9qZWN0IHByZWZlcmVuY2U6IHJlcGxhY2Ugb2Jzb2xldGUgc3lz
dGVtcyB3aGVuIHByYWN0aWNhbDsgcHJlc2VydmUgYmFja3dhcmRzIGNvbXBhdGliaWxpdHkgb25s
eSB3aGVuIGl0IGlzIGV4cGxpY2l0bHkgcmVxdWlyZWQuCjwhLS0gbWFjaGluZS1tZW1vcnk6ZW5k
IC0tPg==
'@

$cleanB64 = $memoryBlockB64 -replace '\s', ''
try {
  $managedBlock = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($cleanB64))
} catch {
  throw "machine-memory init-mcp: could not decode managed AGENTS.md block. $_"
}
if (-not $managedBlock.EndsWith("`n")) {
  $managedBlock += "`n"
}

$startMarker = '<!-- machine-memory:start -->'
$endMarker = '<!-- machine-memory:end -->'

if (Test-Path -LiteralPath $agentsMd -PathType Leaf) {
  $existing = [System.IO.File]::ReadAllText($agentsMd)
  $action = 'Updated'
} else {
  $existing = ''
  $action = 'Created'
  $parentDir = Split-Path -Parent $agentsMd
  if ($parentDir -and -not (Test-Path -LiteralPath $parentDir)) {
    New-Item -ItemType Directory -Force -Path $parentDir | Out-Null
  }
}

$s = $existing.IndexOf($startMarker)
$e = if ($s -ge 0) { $existing.IndexOf($endMarker, $s) } else { -1 }
if ($s -ge 0 -and $e -ge 0) {
  $after = $existing.Substring($e + $endMarker.Length)
  $out = $existing.Substring(0, $s) + $managedBlock.TrimEnd("`r", "`n") + "`n"
  if ($after) {
    $out += $after.TrimStart("`r", "`n")
    if (-not $out.EndsWith("`n")) {
      $out += "`n"
    }
  }
} else {
  $body = $existing.TrimEnd()
  $managedTrimmed = $managedBlock.TrimEnd("`r", "`n")
  if ($body) {
    $out = "$body`n`n$managedTrimmed`n"
  } else {
    $out = "$managedTrimmed`n"
  }
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($agentsMd, $out, $utf8NoBom)

Write-Host "$action $agentsMd"
Write-Host "Backend  mcp (MCP tools; no CLI)"
Write-Host "Next     connect an OAuth MCP client to https://<worker-url>/mcp"
Write-Host "Docs     https://machine-memory.jfa.dev/mcp/init"
